### ISSUE TITLE
Backend Elements: Wrong proposed titles in 3.0.6

### ISSUE THREAD

**Issue by RobinSchwammborn** [mapbender/mapbender-starter#46]
The print client mask in the backend of the editable applications has minor flaws (Mapbender 3.0.6):

2. [x] Also, there is a tiny typo which could be fixed (active instead of activ).
1. [ ] It has a prefilled title box which should be rather empty.

Take a look at these screenshots:

![print_client_wrongtitle](https://cloud.githubusercontent.com/assets/21199730/25229366/3de906d0-25d0-11e7-8642-c6f79d2254b2.png)
![print_client_typo_tiny](https://cloud.githubusercontent.com/assets/21199730/25229368/40a2daa4-25d0-11e7-9075-d80fb0b50001.png)

Thx for fixing :)

**Comment by astroidex** [comment]
Looks good in file:
* https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/translations/messages.de.yml
* please check with Andriy to find the bug

**Comment by eSlider** [comment]
@RobinSchwammborn, this bug is fixed, but please check it to!

**Comment by RobinSchwammborn** [comment]
The bug still persists in my application. It also occurs in various other backend element settings, e.g. Image Export, Navigation Toolbar, POI, and the Scalebar...please take a look at these proving screenshots:

![backend_imageexport_title](https://cloud.githubusercontent.com/assets/21199730/25395363/224b047c-29e1-11e7-8c59-222012955b4b.png)
![backend_navigation_toolbar_title](https://cloud.githubusercontent.com/assets/21199730/25395366/224ff91e-29e1-11e7-8407-b4ad6b796ab1.png)
![backend_poi_title](https://cloud.githubusercontent.com/assets/21199730/25395365/224c2988-29e1-11e7-9ec8-217dfdfb30b6.png)
![backend_scalebar_title](https://cloud.githubusercontent.com/assets/21199730/25395364/224bec66-29e1-11e7-8253-2d597d6bf1e3.png)
